//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VLADFOM.ITMO.ADONET.Lab3LINQXML
{
    using System;
    using System.Collections.Generic;
    
    public partial class Product
    {
        public int Id { get; set; }
        public string ProductName { get; set; }
        public Nullable<double> Weight { get; set; }
        public Nullable<decimal> Price { get; set; }
        public string ProductCompanyName { get; set; }
        public string Size { get; set; }
        public string Category { get; set; }
        public Nullable<bool> IsThisNewProduct { get; set; }
        public Nullable<System.DateTime> AdditionDate { get; set; }
    }
}
